### 1) Write a python program to display all the header tags from wikipedia.org.

In [1]:
import  requests                #import the libraries requests and BeautifulSoup
from  bs4 import BeautifulSoup

url_link = 'https://en.wikipedia.org/wiki/Main_Page'         #pass a URL into a variable

request = requests.get(url_link)             #use the request library to fetch the URL

soup = BeautifulSoup(request.content,'html.parser')        #create a BeautifulSoup object

heading = ['h1','h2','h3','h4','h5','h6']            # creating a list of all common heading

for i in soup.find_all(heading):            #iterate over all the heading using find_all() method
    print(i.name + ' - ' + i.text.strip())

h1 - Main Page
h2 - From today's featured article
h2 - Did you know ...
h2 - In the news
h2 - On this day
h2 - Today's featured picture
h2 - Other areas of Wikipedia
h2 - Wikipedia's sister projects
h2 - Wikipedia languages
h2 - Navigation menu
h3 - Personal tools
h3 - Namespaces
h3 - Variants
expanded
collapsed
h3 - Views
h3 - More
expanded
collapsed
h3 - Search
h3 - Navigation
h3 - Contribute
h3 - Tools
h3 - Print/export
h3 - In other projects
h3 - Languages

### 2) Write a python program to display IMDB’s Top rated 100 movies’ data (i.e. name, rating, year of release) and make data frame

In [2]:
import pandas as pd
import numpy as np

import requests
from bs4 import BeautifulSoup


# Creating the lists we want to write into
titles = []
years = []
imdb_ratings = []
ranking = []

pages = np.arange(1, 101, 50)
pages

# Storing each of the urls of 50 movies 
for page in pages:
    # Getting the contents from the each url
    page = requests.get('https://www.imdb.com/search/title/?groups=top_1000&start=' + str(page) + '&ref_=adv_nxt')
    soup = BeautifulSoup(page.text, 'html.parser')
    
    # Aiming the part of the html we want to get the information from
    movie_div = soup.find_all('div', class_='lister-item mode-advanced')
    

    
    for movie in movie_div:
        # Scraping the movie's name
        name = movie.h3.a.text
        titles.append(name)
        
        # Scraping the movie's rank
        rank = movie.h3.find('span', class_='lister-item-index unbold text-primary').text
        ranking.append(rank)
        
        # Scraping the movie's year
        year = movie.h3.find('span', class_='lister-item-year').text.strip('()')
        years.append(year)
        
        # Scraping the rating
        imdb = float(movie.strong.text)
        imdb_ratings.append(imdb)
        
movies = pd.DataFrame({'Movie':titles,
                       '   Year':years,
                       'IMDB_rating':imdb_ratings,
                      'Rank of movie':ranking})

movies.head()

                     Movie    Year  IMDB_rating Rank of movie
0  Spider-Man: No Way Home    2021          8.8            1.
1               The Matrix    1999          8.7            2.
2               Home Alone    1990          7.6            3.
3    It's a Wonderful Life    1946          8.6            4.
4                 Die Hard    1988          8.2            5.

### 3) Write a python program to display IMDB’s Top rated 100 Indian movies’ data (i.e. name, rating, year of release) and make data frame.

In [3]:
import pandas as pd
import numpy as np

import requests
from bs4 import BeautifulSoup


# Creating the lists we want to write into
titles = []
ranking = []
years = []
imdb_ratings = []


# Getting the contents from the url

page = requests.get('https://www.imdb.com/india/top-rated-indian-movies/?sort=')
soup = BeautifulSoup(page.text, 'html.parser')
    
# Aiming the part of the html we want to get the information from
movies = soup.find('tbody', class_='lister-list').find_all("tr")
       
for movie in movies:
    # Scraping the movie's rank 
    rank = movie.find('td', class_="titleColumn").get_text(strip=True).split('.')[0]
    ranking.append(rank)
    
    # Scraping the movie's name
    name = movie.find('td', class_="titleColumn").a.text
    titles.append(name)
    
    # Scraping the movie's year
    year = movie.find('td', class_="titleColumn").span.text.strip('()')
    years.append(year)
    
    # Scraping the rating
    imdb = float(movie.find('td', class_='ratingColumn imdbRating').strong.text)
    imdb_ratings.append(imdb)
    
    
_movies = pd.DataFrame({'Movie Rank':ranking,
                        'Movie Name':titles,
                       'release year of movie':years,
                       'IMDB_rating':imdb_ratings})

_movies

    Movie Rank            Movie Name release year of movie  IMDB_rating
0            1              Jai Bhim                  2021          8.5
1            2     Pariyerum Perumal                  2018          8.5
2            3               Nayakan                  1987          8.5
3            4            Anbe Sivam                  2003          8.5
4            5     C/o Kancharapalem                  2018          8.5
..         ...                   ...                   ...          ...
245        246                  Darr                  1993          7.6
246        247  Kabhi Haan Kabhi Naa                  1994          7.6
247        248         Kapoor & Sons                  2016          7.6
248        249                Newton                  2017          7.6
249        250                 Aamir                  2008          7.6

[250 rows x 4 columns]

### 4) Write a python program to scrape product name, price and discounts from https://meesho.com/bagsladies/pl/p7vbp .

In [7]:
import pandas as pd
import numpy as np

import requests
from bs4 import BeautifulSoup


# Creating the lists we want to write into
product_name = []
price = []
discounts = []

# Getting the contents from the url
page = requests.get('https://meesho.com/bags%02ladies/pl/p7vbp')
soup = BeautifulSoup(page.text, 'lxml')
    
# Aiming the part of the html we want to get the information from
    
all_product = soup.find('div', attrs= {'class':"sc-gsDKAQ Grid__Row-sc-4ki5nk-0 iQiJjX gfsqfL products"}).find_all('div', attrs = {'class':"sc-dkPtRN ProductList__GridCol-sc-8lnc8o-0 FjWWx jMkQHN"})


for product in all_product:
        
    #Scraping the product's name
    name = product.find('a', href=True).div.find('div',attrs = {'class':"Card__BaseCard-sc-b3n78k-0 dUNFgg NewProductCard__DetailCard_Desktop-sc-j0e7tu-2 fqvaeS NewProductCard__DetailCard_Desktop-sc-j0e7tu-2 fqvaeS"})
    
    names = name.p.text
    product_name.append(names)
    
       
    #Scraping the product's price
    prices = product.find('div', attrs = {'class':"Card__BaseCard-sc-b3n78k-0 iLPHgK NewProductCard__PriceRow-sc-j0e7tu-5 eyya-Dr NewProductCard__PriceRow-sc-j0e7tu-5 eyya-Dr"}).p.text
    price.append(prices)
     
    #Scraping the discount on products
    dis = product.find('div', attrs = {'class':"Card__BaseCard-sc-b3n78k-0 iLPHgK NewProductCard__PriceRow-sc-j0e7tu-5 eyya-Dr NewProductCard__PriceRow-sc-j0e7tu-5 eyya-Dr"}).span.text
    discounts.append(dis)
    

bags = pd.DataFrame({'Product Name': product_name,
                    'Original Price': price,
                     'Discount': discounts})
bags

                                         Product Name Original Price Discount
0   khatushyam collection  Women Handbag - Extra S...           ₹474  21% off
1                                      bandhani thela           ₹325  30% off
2   Women's Handbag With Sling Bag & Wristlet (Set...           ₹521  19% off
3   AZED Collections Women's PU Leather Handbag - ...           ₹666  15% off
4   Woman Ladies Girls Handmade bags for women zip...           ₹484  21% off
5   YouRdreamZ jute lunch bag shopping bag for men...           ₹235  30% off
6                                    Shoulder Handbag           ₹484  21% off
7   Genuane  Leather Latest Trendy Fashion Ladies ...          ₹2761   4% off
8                                             Handbag           ₹516  19% off
9                                     ELEGANT HANDBAG           ₹329  30% off
10  Women's Nylon Fabric Casual Hand Bag (Sandal w...           ₹535  19% off
11                                STYLISH WOMEN PURSE           ₹584  17% off
12                                STYLISH WOMEN PURSE           ₹584  17% off
13                                STYLISH WOMEN PURSE           ₹634  16% off
14                                 STYLISH WOMEN BAGS           ₹615  16% off
15                          Style big woman side bag            ₹289  30% off

### 5) Write a python program to scrape cricket rankings from icc-cricket.com. You have to scrape:

#####       a) Top 10 ODI teams in men’s cricket along with the records for matches, points and rating.

In [ ]:
import pandas as pd
import numpy as np

import requests
from bs4 import BeautifulSoup


# Creating the lists we want to write into
team_rank = []
team_name = []
matches = []
points = []
rating = []

# Getting the contents from the url
page = requests.get('https://www.icc-cricket.com/rankings/mens/team-rankings/odi')
soup = BeautifulSoup(page.text, 'lxml')


top_teams = soup.tbody.find_all('tr')

for teams in top_teams:
    
    #scraping of teams rank.
    rank = teams.td.text
    team_rank.append(rank)
    
    #scraping of teams name.
    name = teams.find('td', class_="rankings-block__banner--team-name").text
    team_name.append(name)

    #scraping of matches.
    mat = teams.find('td', class_="rankings-block__banner--matches").text
    matches.append(mat)
    
    #scraping of points.
    point = teams.find('td', class_="rankings-block__banner--points").text
    points.append(point)
    
    #scraping of rating.
    rate = teams.find('td', class_="rankings-block__banner--rating u-text-right").text
    rating.append(rate)
    
    
        
rank_of_teams = pd.DataFrame({'Team rank': team_rank,
                    'Team name': team_name,
                     'Matches': matches,
                    'Points': points,
                    'Rating': rating})
rank_of_teams